
USE [OnyxToMSCRM_STAGE]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE OBJECT_ID = OBJECT_ID(N'dbo.Contact') AND type in (N'U'))
BEGIN
	DROP TABLE dbo.Contact
END
GO

CREATE TABLE [dbo].[Contact]
(
	[ContactId] [uniqueidentifier] NOT NULL DEFAULT(NEWID()),
	[DefaultPriceLevelId] [uniqueidentifier] NULL,
	[CustomerSizeCode] [int] NULL,
	[CustomerTypeCode] [int] NULL,
	[PreferredContactMethodCode] [int] NULL,
	[LeadSourceCode] [int] NULL,
	[OriginatingLeadId] [uniqueidentifier] NULL,
	[OwningBusinessUnit] [uniqueidentifier] NULL,
	[PaymentTermsCode] [int] NULL,
	[ShippingMethodCode] [int] NULL,
	[ParticipatesInWorkflow] [bit] NULL,
	[IsBackofficeCustomer] [bit] NULL,
	[Salutation] [nvarchar](100) NULL,
	[JobTitle] [nvarchar](255) NULL,
	[FirstName] [nvarchar](100) NULL,
	[Department] [nvarchar](255) NULL,
	[NickName] [nvarchar](50) NULL,
	[MiddleName] [nvarchar](50) NULL,
	[LastName] [nvarchar](100) NULL,
	[Suffix] [nvarchar](100) NULL,
	[YomiFirstName] [nvarchar](150) NULL,
	[FullName] [nvarchar](160) NULL,
	[YomiMiddleName] [nvarchar](150) NULL,
	[YomiLastName] [nvarchar](150) NULL,
	[Anniversary] [datetime] NULL,
	[BirthDate] [datetime] NULL,
	[GovernmentId] [nvarchar](50) NULL,
	[YomiFullName] [nvarchar](450) NULL,
	[Description] [nvarchar](max) NULL,
	[EmployeeId] [nvarchar](50) NULL,
	[GenderCode] [int] NULL,
	[AnnualIncome] [money] NULL,
	[HasChildrenCode] [int] NULL,
	[EducationCode] [int] NULL,
	[WebSiteUrl] [nvarchar](255) NULL,
	[FamilyStatusCode] [int] NULL,
	[FtpSiteUrl] [nvarchar](200) NULL,
	[EMailAddress1] [nvarchar](200) NULL,
	[SpousesName] [nvarchar](100) NULL,
	[AssistantName] [nvarchar](100) NULL,
	[EMailAddress2] [nvarchar](100) NULL,
	[AssistantPhone] [nvarchar](50) NULL,
	[EMailAddress3] [nvarchar](100) NULL,
	[DoNotPhone] [bit] NULL,
	[ManagerName] [nvarchar](100) NULL,
	[ManagerPhone] [nvarchar](50) NULL,
	[DoNotFax] [bit] NULL,
	[DoNotEMail] [bit] NULL,
	[DoNotPostalMail] [bit] NULL,
	[DoNotBulkEMail] [bit] NULL,
	[DoNotBulkPostalMail] [bit] NULL,
	[AccountRoleCode] [int] NULL,
	[TerritoryCode] [int] NULL,
	[IsPrivate] [bit] NULL,
	[CreditLimit] [money] NULL,
	[CreatedOn] [datetime] NULL,
	[CreditOnHold] [bit] NULL,
	[CreatedBy] [uniqueidentifier] NULL,
	[ModifiedOn] [datetime] NULL,
	[ModifiedBy] [uniqueidentifier] NULL,
	[NumberOfChildren] [int] NULL,
	[ChildrensNames] [nvarchar](255) NULL,
	[VersionNumber] [timestamp] NULL,
	[MobilePhone] [nvarchar](50) NULL,
	[Pager] [nvarchar](50) NULL,
	[Telephone1] [nvarchar](50) NULL,
	[Telephone2] [nvarchar](50) NULL,
	[Telephone3] [nvarchar](50) NULL,
	[Fax] [nvarchar](50) NULL,
	[Aging30] [money] NULL,
	[StateCode] [int] NOT NULL,
	[Aging60] [money] NULL,
	[StatusCode] [int] NULL,
	[Aging90] [money] NULL,
	[PreferredSystemUserId] [uniqueidentifier] NULL,
	[PreferredServiceId] [uniqueidentifier] NULL,
	[MasterId] [uniqueidentifier] NULL,
	[PreferredAppointmentDayCode] [int] NULL,
	[PreferredAppointmentTimeCode] [int] NULL,
	[DoNotSendMM] [bit] NULL,
	[Merged] [bit] NULL,
	[ExternalUserIdentifier] [nvarchar](50) NULL,
	[SubscriptionId] [uniqueidentifier] NULL,
	[PreferredEquipmentId] [uniqueidentifier] NULL,
	[LastUsedInCampaign] [datetime] NULL,
	[TransactionCurrencyId] [uniqueidentifier] NULL,
	[OverriddenCreatedOn] [datetime] NULL,
	[ExchangeRate] [decimal](23, 10) NULL,
	[ImportSequenceNumber] [int] NULL,
	[TimeZoneRuleVersionNumber] [int] NULL,
	[UTCConversionTimeZoneCode] [int] NULL,
	[AnnualIncome_Base] [money] NULL,
	[CreditLimit_Base] [money] NULL,
	[Aging60_Base] [money] NULL,
	[Aging90_Base] [money] NULL,
	[Aging30_Base] [money] NULL,
	[OwnerId] [uniqueidentifier] NOT NULL,
	[CreatedOnBehalfBy] [uniqueidentifier] NULL,
	[IsAutoCreate] [bit] NULL,
	[ModifiedOnBehalfBy] [uniqueidentifier] NULL,
	[ParentCustomerId] [uniqueidentifier] NULL,
	[ParentCustomerIdType] [int] NULL,
	[ParentCustomerIdName] [nvarchar](4000) NULL,
	[OwnerIdType] [int] NOT NULL,
	[ParentCustomerIdYomiName] [nvarchar](4000) NULL,
	[MTB_AuthorAAP] [bit] NULL,
	[MTB_BillingFax] [nvarchar](50) NULL,
	[MTB_BillingMainPhone] [nvarchar](50) NULL,
	[MTB_CustomerSubTypeCode] [int] NULL,
	[MTB_DonotallowNewsletter] [bit] NULL,
	[MTB_DonotallowProductAlertsTrainingAnnoun] [bit] NULL,
	[MTB_EmailStatus] [int] NULL,
	[MTB_ID] [nvarchar](100) NULL,
	[MTB_ID_Search] [int] NULL,
	[MTB_InstructorLecturer] [bit] NULL,
	[MTB_IsTrainer] [bit] NULL,
	[MTB_ITContact] [bit] NULL,
	[MTB_KnowledgeableResource] [bit] NULL,
	[MTB_LanguagePreference] [int] NULL,
	[MTB_MailStatus] [int] NULL,
	[MTB_MTBActivated] [bit] NULL,
	[MTB_MTBStatisticalSoftwareUsed2] [int] NULL,
	[MTB_PrimaryPhone] [int] NULL,
	[MTB_ProfileComplete] [bit] NULL,
	[MTB_PurchasingAgent] [bit] NULL,
	[MTB_QualityCompanionActivated] [bit] NULL,
	[MTB_QualityCompanionUsed2] [int] NULL,
	[MTB_QualityTrainerUsed2] [int] NULL,
	[MTB_SendToGPINC] [bit] NULL,
	[MTB_SendToGPLTD] [bit] NULL,
	[MTB_SendToGPPTY] [bit] NULL,
	[MTB_SendToGPSARL] [bit] NULL,
	[MTB_TrainingCalendarColor] [nvarchar](25) NULL,
	[MTB_VOIPPhone] [nvarchar](50) NULL,
	[MTB_WorkshopCoordinator] [bit] NULL,
	[MTB_CampaignId] [uniqueidentifier] NULL,
	[MTB_SiteId] [uniqueidentifier] NULL,
	[MTB_AddressValid] [bit] NULL,
	[MTB_PendingAccountName] [nvarchar](255) NULL,
	[dnb_dnbinitialassociationdate] [datetime] NULL,
	[dnb_dnbinitialassociationstatus] [nvarchar](25) NULL,
	[dnb_DBCompanyId] [uniqueidentifier] NULL,
	[dnb_dbcontactid] [uniqueidentifier] NULL,
	[MTB_overriderequiredfields] [bit] NULL,
   	[MTB_FlexAdminLetter][nvarchar](10) NULL,
   	[MTB_consultant] [bit] NULL,
   	[MTB_Spam] [bit] NULL,
	[RowAction] [nvarchar](25) NULL
	)
	ON [PRIMARY]

GO
	
	
	
